In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from tqdm import tqdm

## Loading the data

In [2]:
df_productcodes = pd.read_csv("/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/BACI_HS17_V202601/product_codes_HS17_V202601.csv")
df_contrycodes = pd.read_csv("/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/BACI_HS17_V202601/country_codes_V202601.csv")
df_conversion_HS17_GSEC11 = pd.read_excel(
    "/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/other/HS6_to_GTAP11.xlsx",
    sheet_name="H5",
    header=1
    )
df_conversion_HS22_GSEC11 = pd.read_excel(
    "/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/other/HS6_to_GTAP11.xlsx",
    sheet_name="H6",
    header=1,
)

In [3]:
df_all = pd.DataFrame()
for data in tqdm(Path("/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/BACI_HS17_V202601").glob("BACI_*.csv")):
    df = pd.read_csv(data)
    df_all = pd.concat([df_all, df], ignore_index=True)

df_all = df_all.rename(columns={
    "t": "Year",
    "k": "HS6",
    "i": "Exporter",
    "j": "Importer",
    "v": "k$",
    "q": "Quantity",
})

8it [00:23,  2.94s/it]

### Merging the data in one df

In [4]:
df_merge_1 = pd.merge(
    df_all,
    df_contrycodes[["country_code", "country_iso3"]],
    left_on="Exporter",
    right_on="country_code",
    how="left",
)
df_merge_1 = (
    df_merge_1.drop(columns="Exporter")
    .rename(columns={"country_iso3": "Exporter"})
    .drop(columns="country_code")
)

In [5]:
df_merge_2 = pd.merge(
    df_merge_1,
    df_contrycodes[["country_code", "country_iso3"]],
    left_on="Importer",
    right_on="country_code",
    how="left",
)
df_merge_2 = (
    df_merge_2.drop(columns="Importer")
    .rename(columns={"country_iso3": "Importer"})
    .drop(columns="country_code")
)

In [6]:
df_merge_3 = pd.merge(
    df_merge_2,
    df_productcodes[["code", "description"]],
    left_on="HS6",
    right_on="code",
    how="left",
)
df_merge_3 = df_merge_3.drop(columns="HS6").rename(columns={"code": "HS6_code"})

In [7]:
df_merge_3

,Year,k$,Quantity,Exporter,Importer,HS6_code,description
0,2020,1.250,0.003,AFG,AND,710399,Stones: precious (other than diamonds) and sem...
1,2020,0.198,0.001,AFG,AGO,300431,"Medicaments: containing insulin, for therapeut..."
2,2020,1.287,0.007,AFG,AGO,840999,Engines: parts for internal combustion piston ...
3,2020,31.057,169.800,AFG,AZE,251512,"Marble and travertine: merely cut, by sawing o..."
4,2020,0.047,0.009,AFG,ARG,391000,Silicones: in primary forms
...,...,...,...,...,...,...,...
89207216,2019,25.426,1.218,ZMB,BFA,722830,"Steel, alloy: bars and rods, hot-rolled, hot-d..."
89207217,2019,21.926,1.000,ZMB,BFA,722880,"Steel, alloy or non-alloy: hollow drill bars a..."
89207218,2019,16.927,NaN,ZMB,BFA,820719,"Tools, interchangeable: rock drilling or earth..."
89207219,2019,320.518,59.400,ZMB,URY,240120,Tobacco: partly or wholly stemmed or stripped
89207220,2019,0.026,NaN,ZMB,URY,482390,"Paper pulp, paper, paperboard, cellulose waddi..."

In [8]:
df_conversion_HS17_GSEC11.head()

,Classification,Code,Description,Code Parent,GSEC3,GSEC3_rev
0,H5,10121,"Horses; live, pure-bred breeding animals",101,CTL,CTL
1,H5,10129,"Horses; live, other than pure-bred breeding an...",101,CTL,CTL
2,H5,10130,Asses; live,101,CTL,CTL
3,H5,10190,Mules and hinnies; live,101,CTL,CTL
4,H5,10221,"Cattle; live, pure-bred breeding animals",102,CTL,CTL

In [9]:
df_merge_4 = pd.merge(
    df_merge_3,
    df_conversion_HS17_GSEC11[["Code", "GSEC3_rev"]],
    left_on="HS6_code",
    right_on="Code",
    how="left",
)
df_merge_4 = df_merge_4.drop(columns="Code").rename(columns={"GSEC3_rev": "GSEC3_code"})

In [10]:
df_merge_4.head()

,Year,k$,Quantity,Exporter,Importer,HS6_code,description,GSEC3_code
0,2020,1.250,0.003,AFG,AND,710399,Stones: precious (other than diamonds) and sem...,OMF
1,2020,0.198,0.001,AFG,AGO,300431,"Medicaments: containing insulin, for therapeut...",BPH
2,2020,1.287,0.007,AFG,AGO,840999,Engines: parts for internal combustion piston ...,MVH
3,2020,31.057,169.800,AFG,AZE,251512,"Marble and travertine: merely cut, by sawing o...",oxt
4,2020,0.047,0.009,AFG,ARG,391000,Silicones: in primary forms,CHM

In [11]:
df_clean = df_merge_4.groupby(["Year", "Exporter", "Importer", "GSEC3_code"]).agg({"k$": "sum", "Quantity": "sum"}).reset_index()

In [12]:
df_clean.head(20)

    Year Exporter Importer GSEC3_code      k$  Quantity
0   2017      ABW      AUT        EEQ   0.160     0.001
1   2017      ABW      AUT        ELE  64.057     0.007
2   2017      ABW      AUT        MVH   0.285     0.004
3   2017      ABW      AUT        OMF  44.876     0.046
4   2017      ABW      BEL        EEQ   7.547     0.060
5   2017      ABW      BEL        ELE   9.000     0.000
6   2017      ABW      BEL        I_S   5.596    49.580
7   2017      ABW      BEL        OMF   6.896     0.002
8   2017      ABW      BGR        OMF   1.863     0.014
9   2017      ABW      BHR        OCR   0.324     0.530
10  2017      ABW      BHR        OFD   0.056     0.100
11  2017      ABW      BHR        OME  59.543    19.750
12  2017      ABW      BHR        PCR   0.312     4.000
13  2017      ABW      BHR        V_F   0.014     0.000
14  2017      ABW      BIH        ELE   0.879     0.003
15  2017      ABW      BIH        WAP   0.012     0.001
16  2017      ABW      CAN        BPH   0.053     0.005
17  2017      ABW      CAN        CHM   1.349     0.047
18  2017      ABW      CAN        EEQ   0.141     0.001
19  2017      ABW      CAN        ELE   3.867     0.000

In [13]:
df_clean.to_parquet(
    "/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/GTAP11_grouped_data.parquet", index=False
)

In [14]:
# df_merge_4.to_parquet(
#     "/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/BACI_HS17_V202601/df_merge.parquet",
#     index=False,
# )

## Using the full data

In [45]:
import pandas as pd

df_clean = pd.read_parquet(
    "/Users/pacomelefebvre/Desktop/HCSP2/MIRAGE/data/GTAP11_grouped_data.parquet"
)

In [46]:
df_clean.head()

   Year Exporter Importer GSEC3_code      k$  Quantity
0  2017      ABW      AUT        EEQ   0.160     0.001
1  2017      ABW      AUT        ELE  64.057     0.007
2  2017      ABW      AUT        MVH   0.285     0.004
3  2017      ABW      AUT        OMF  44.876     0.046
4  2017      ABW      BEL        EEQ   7.547     0.060

In [47]:
EU27 = [
    "AUT",
    "BEL",
    "BGR",
    "HRV",
    "CYP",
    "CZE",
    "DNK",
    "EST",
    "FIN",
    "FRA",
    "DEU",
    "GRC",
    "HUN",
    "IRL",
    "ITA",
    "LVA",
    "LTU",
    "LUX",
    "MLT",
    "NLD",
    "POL",
    "PRT",
    "ROU",
    "SVK",
    "SVN",
    "ESP",
    "SWE",
]

eu_map = {code: "UE27" for code in EU27}

df_UE = df_clean.copy().replace({"Exporter": eu_map, "Importer": eu_map})

In [48]:
df_UE_clean = df_UE[(df_UE["Exporter"] == "UE27") & (df_UE["Importer"] == "CHN") | (df_UE["Exporter"] == "CHN") & (df_UE["Importer"] == "UE27")]

In [49]:
df_UE_clean.columns

Index(['Year', 'Exporter', 'Importer', 'GSEC3_code', 'k$', 'Quantity'], dtype='str')

In [50]:
exports_ue_chine = (
    df_UE_clean[(df_UE_clean["Exporter"] == "UE27") & (df_UE_clean["Importer"] == "CHN")]
    .groupby("GSEC3_code")["k$"]
    .sum()
)
imports_ue_chine = (
    df_UE_clean[(df_UE_clean["Exporter"] == "CHN") & (df_UE_clean["Importer"] == "UE27")]
    .groupby("GSEC3_code")["k$"]
    .sum()
)
df_bilan = pd.DataFrame(
    {
        "Exports_UE_vers_Chine": exports_ue_chine,
        "Imports_UE_depuis_Chine": imports_ue_chine,
    }
).fillna(0)

df_bilan["Solde_commercial"] = (
    df_bilan["Exports_UE_vers_Chine"] - df_bilan["Imports_UE_depuis_Chine"]
)
df_bilan = df_bilan.reset_index()

In [52]:
df_bilan

,GSEC3_code,Exports_UE_vers_Chine,Imports_UE_depuis_Chine,Solde_commercial
0,BPH,1.535093e+08,6.648059e+07,8.702868e+07
1,B_T,1.928527e+07,2.100638e+06,1.718463e+07
2,CHM,1.579529e+08,1.794961e+08,-2.154324e+07
3,CMT,1.875632e+06,4.438978e+06,-2.563347e+06
4,COA,8.123226e+04,4.114511e+05,-3.302188e+05
5,CTL,1.707833e+05,1.298391e+03,1.694849e+05
6,C_B,2.054021e+05,3.817410e+02,2.050204e+05
7,EEQ,1.470241e+08,5.897667e+08,-4.427426e+08
8,ELE,2.407716e+08,1.303935e+09,-1.063163e+09
9,ELY,0.000000e+00,5.620000e-01,-5.620000e-01
10,FMP,4.088978e+07,1.898363e+08,-1.489466e+08
11,FRS,8.222470e+06,8.400095e+05,7.382460e+06
12,FSH,1.146910e+06,1.482652e+05,9.986449e+05
13,GAS,1.456388e+06,5.832516e+05,8.731359e+05
14,GDT,0.000000e+00,3.988700e+01,-3.988700e+01
15,GRO,3.997319e+06,5.118318e+04,3.946135e+06
16,I_S,2.240920e+07,3.913741e+07,-1.672820e+07
17,LEA,2.812327e+07,1.523720e+08,-1.242487e+08
18,LUM,1.066719e+07,2.382933e+07,-1.316214e+07
19,MIL,1.368202e+07,3.280696e+04,1.364921e+07
20,MVH,3.050046e+08,1.237152e+08,1.812894e+08
21,NFM,5.487653e+07,3.139895e+07,2.347758e+07
22,NMM,1.471877e+07,6.062413e+07,-4.590536e+07
23,OAP,4.079619e+06,2.285032e+06,1.794587e+06
24,OCR,2.203125e+06,4.237388e+06,-2.034264e+06
25,OFD,4.212388e+07,4.116146e+07,9.624182e+05
26,OIL,1.332143e+05,6.914800e+01,1.331452e+05
27,OME,3.077838e+08,3.449997e+08,-3.721581e+07
28,OMF,5.527495e+07,3.050349e+08,-2.497599e+08
29,OMT,3.301126e+07,1.413247e+06,3.159801e+07
30,OSD,2.711099e+05,1.950504e+06,-1.679394e+06
31,OTN,1.000076e+08,9.043735e+07,9.570277e+06
32,OXT,4.097655e+05,2.386672e+04,3.858988e+05
33,PCR,9.062660e+02,1.760386e+05,-1.751323e+05
34,PDR,1.678400e+01,7.034360e+02,-6.866520e+02
35,PFB,1.279376e+05,2.323511e+04,1.047025e+05
36,PPP,3.219253e+07,2.855012e+07,3.642403e+06
37,P_C,1.186574e+06,8.797474e+06,-7.610900e+06
38,RPP,3.972100e+07,1.289471e+08,-8.922606e+07
39,SGR,2.254215e+04,9.749529e+03,1.279262e+04
40,TEX,1.870398e+07,1.337534e+08,-1.150495e+08
41,VOL,4.136853e+06,2.165847e+06,1.971006e+06
42,V_F,9.332665e+05,5.201365e+06,-4.268099e+06
43,WAP,2.342137e+07,2.903007e+08,-2.668793e+08
44,WHT,2.636829e+06,2.238914e+03,2.634590e+06
45,WOL,2.980048e+05,1.121363e+06,-8.233579e+05
46,fmp,9.154840e+04,1.055433e+06,-9.638843e+05
47,oap,3.545630e+02,9.120000e-01,3.536510e+02
48,ofd,4.339621e+04,1.547858e+04,2.791763e+04
49,ome,9.293759e+04,1.610953e+06,-1.518015e+06
50,oxt,1.984741e+07,5.521900e+06,1.432551e+07
51,v_f,3.573500e+01,1.237900e+01,2.335600e+01
52,wap,2.297858e+03,4.936838e+04,-4.707053e+04